// Create web server
// 1. npm init -y
// 2. npm install express
// 3. npm install body-parser
// 4. npm install cors
// 5. npm install nodemon
// 6. npm install mongoose
// 7. npm install dotenv
// 8. npm install bcrypt
// 9. npm install jsonwebtoken
// 10. npm install express-validator
// 11. npm install cookie-parser
// 12. npm install express-session
// 13. npm install multer
// 14. npm install passport
// 15. npm install passport-local
// 16. npm install passport-local-mongoose
// 17. npm install connect-flash
// 18. npm install method-override
// 19. npm install connect-mongo
// 20. npm install socket.io
// 21. npm install socket.io-client
// 22. npm install socket.io-redis
// 23. npm install redis
// 24. npm install ioredis
// 25. npm install moment
// 26. npm install mongoose-unique-validator
// 27. npm install mongoose-findorcreate
// 28. npm install mongoose-autopopulate
// 29. npm install mongoose-lean-virtuals
// 30. npm install mongoose-paginate-v2
// 31. npm install mongoose-mongodb-errors
// 32. npm install mongoose-deep-populate-v2
// 33. npm install mongoose-regex-search
// 34. npm install mongoose-regex-search
// 35. npm install mongoose-regex-search
// 36. npm install mongoose-regex-search
// 37. npm install mongoose-regex-search
// 38. npm install mongoose-regex-search
// 39. npm install mongoose-regex-search
// 40. npm install mongoose-regex-search
// 41. npm install mongoose-regex-search
// 42. npm install mongoose-regex-search
// 43. npm install mongoose-regex-search
// 44. npm install mongoose-regex-search
// 45. npm install mongoose-regex-search
// 46. npm install mongoose-regex-search
// 47. npm install mongoose-regex-search
// 48. npm install mongoose-regex-search
// 49. npm install mongoose-regex-search
// 50